apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teoschool
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sallby/k8s-deploy.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: teoschool

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
