apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  namespace: teoschool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: crdjiby.azurecr.io/img_webui:v1.0.0
        ports:
        - containerPort: 80