apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: teoschool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: crdjiby.azurecr.io/img_worker:v1.0.0
        ports:
        - containerPort: 80

