name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f redis.yaml
        kubectl apply -f hasher.yaml
        kubectl apply -f rng.yaml
        kubectl apply -f worker.yaml
        kubectl apply -f webui.yaml

    - name: Get LoadBalancer IP
      id: webui
      run: |
        WEBUI_IP=$(kubectl get svc webui-service -n teoschool -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "L'adresse IP du service WebUI est : $WEBUI_IP"
      shell: bash

    - name: Deploy Prometheus
      run: |
        kubectl apply -f prometheus.yaml

    - name: Deploy Grafana
      run: |
        kubectl apply -f grafana.yaml

    - name: Get LoadBalancer IP
      id: prometheus
      run: |
        PROMETHEUS_IP=$(kubectl get svc prometheus-service -n teoschool -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "L'adresse IP du service prometheus-service est : $PROMETHEUS_IP"
      shell: bash

    - name: Get LoadBalancer IP
      id: grafana
      run: |
        GRAFANA_IP=$(kubectl get svc grafana-service -n teoschool -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "L'adresse IP du service prometheus-service est : $GRAFANA_IP"
      shell: bash