name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose deploy or delete'
        required: true
        default: 'deploy'
        options:
          - 'deploy'
          - 'delete'

jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Execute Deploy or Delete
        run: |
          if [ "$CHOICE" == "deploy" ]; then
            # Logique à exécuter pour le déploiement
          elif [ "$CHOICE" == "delete" ]; then
            # Logique à exécuter pour la suppression
          else
            echo "Choix invalide"
            exit 1
          fi
