name: Your Workflow Name

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose deploy or delete'
        required: true
        default: 'deploy'
        options:
          - 'deploy'
          - 'delete'

jobs:
  deploy-or-delete:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Execute Deploy or Delete
        run: |
          if [ "${{ github.event.inputs.choice }}" == "deploy" ]; then
            echo "Deploying..."
            echo "Executing deploy workflow..."
            echo "::set-output name=workflow::deploy.yml"
          elif [ "${{ github.event.inputs.choice }}" == "delete" ]; then
            echo "Deleting..."
            echo "Executing delete workflow..."
            echo "::set-output name=workflow::delete.yml"
          else
            echo "Invalid choice"
            exit 1
          fi

      - name: Trigger Selected Workflow
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const workflow = ${{ steps.execute.outputs.workflow }};
            console.log(`Triggering workflow: ${workflow}`);
            const response = await octokit.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: workflow
            });
            console.log(response.data);
