name: Your Workflow Name

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose deploy or delete'
        required: true
        default: 'deploy'
        options:
          - 'deploy'
          - 'delete'

jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Execute Deploy or Delete
        run: |
          if [ "${{ github.event.inputs.choice }}" == "deploy" ]; then
            # Logique pour le déploiement
          elif [ "${{ github.event.inputs.choice }}" == "delete" ]; then
            # Logique pour la suppression
          else
            echo "Invalid choice"
            exit 1
          fi