name: Deploy Prometheus and Grafana on AKS

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Check and Install Az CLI
        run: |
          if ! command -v az &> /dev/null
          then
            echo "Az CLI not found. Installing..."
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi
        shell: bash

      - name: Login to Azure
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get credentials
        run: az aks get-credentials --resource-group re-teoSchool-djiby --name aks-djiby

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
        shell: bash

      - name: Create a namespace for Prometheus and Grafana
        run: kubectl create ns prometheus

      - name: Install Prometheus using Helm
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus

      #- name: Port-forward Prometheus
      #  run: kubectl port-forward -n prometheus svc/prometheus-prometheus-operated 9090:9090
      #  background: true

      - name: Get Prometheus Admin Password
        run: |
          admin_password=$(kubectl get secret -n prometheus prometheus-prometheus-grafana -o jsonpath='{.data.admin-password}' | base64 -d)
          echo "Prometheus Admin Password: $admin_password"
        id: prometheus_password

      - name: Port-forward Grafana
        run: kubectl port-forward -n prometheus svc/prometheus-grafana 3000:80 &

      - name: Get Grafana Admin Password
        run: |
          admin_password=$(kubectl get secret -n prometheus prometheus-grafana -o jsonpath='{.data.admin-password}' | base64 -d)
          echo "Grafana Admin Password: $admin_password"
        id: grafana_password
