name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Other Workflows
        uses: actions/checkout@v2

      - name: Run WebUI Workflow
        run: |
          git clone https://github.com/sallby/webui-TeoSchool-Djiby.git
          cd webui-TeoSchool-Djiby
          gh workflow run .github/workflows/build-img-webui.yml

      - name: Run Hasher Workflow
        run: |
          git clone https://github.com/sallby/hasher-TeoSchool-Djiby.git
          cd hasher-TeoSchool-Djiby
          gh workflow run .github/workflows/build-imag-hasher.yml

      - name: Run RNG Workflow
        run: |
          git clone https://github.com/sallby/rng-TeoSchool-Djiby.git
          cd rng-TeoSchool-Djiby
          gh workflow run .github/workflows/build-img-rng.yml

      - name: Run Worker Workflow
        run: |
          git clone https://github.com/sallby/worker-TeoSchool-Djiby.git
          cd worker-TeoSchool-Djiby
          gh workflow run .github/workflows/build-img-worker.yml
